export const SELECTED_ELEMENT = 'SELECTED_ELEMENT';
export const DESELECT_ELEMENT = 'DESELECT_ELEMENT';
export const CREATE_HOTSPOT = 'CREATE_HOTSPOT';
export const DELETE_HOTSPOT = 'DELETE_HOTSPOT';
export const EDIT_HOTSPOT = 'EDIT_HOTSPOT';
export const SHOW_HOTSPOT = 'SHOW_HOTSPOT';
